<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\OsintToolkit.Core\OsintToolkit.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="DnsClient" Version="1.6.6" />
    <PackageReference Include="XposedOrNot" Version="1.0.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
